PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE drinksList (_id INTEGER PRIMARY KEY AUTOINCREMENT, brand TEXT, variant TEXT, type TEXT NOT NULL, inBar INTEGER DEFAULT 1,COMMON INTEGER DEFAULT 0);
INSERT INTO drinksList VALUES(1,'captain morgan''s','spiced','rum',1,0);
INSERT INTO drinksList VALUES(2,'coca','','cola',0,0);
INSERT INTO drinksList VALUES(3,'','cranberry','juice',1,0);
INSERT INTO drinksList VALUES(4,'smirnoff','','vodka',1,0);
INSERT INTO drinksList VALUES(5,'','london dry','gin',0,0);
INSERT INTO drinksList VALUES(6,'','blanco','tequila',0,0);
INSERT INTO drinksList VALUES(7,'','peach','schnapps',0,0);
INSERT INTO drinksList VALUES(8,'','','lemonade',1,0);
INSERT INTO drinksList VALUES(9,'kraken','spiced','rum',1,0);
INSERT INTO drinksList VALUES(11,'rumbullion','spiced','rum',1,0);
INSERT INTO drinksList VALUES(12,'','parma violet','gin',1,0);
INSERT INTO drinksList VALUES(13,'fee brothers','angostura (orange)','bitters',1,0);
INSERT INTO drinksList VALUES(14,'fee brothers','plumb','bitters',1,0);
INSERT INTO drinksList VALUES(15,'','strawberry','gin',1,0);
INSERT INTO drinksList VALUES(16,'jack daniel''s','tennessee honey','bourbon',0,0);
INSERT INTO drinksList VALUES(17,'','sugar','syrup',1,1);
INSERT INTO drinksList VALUES(19,'','','egg white',0,1);
INSERT INTO drinksList VALUES(20,'','orange','juice',1,0);
INSERT INTO drinksList VALUES(21,'','cranberry','juice',0,0);
INSERT INTO drinksList VALUES(22,'','pineapple','juice',1,0);
INSERT INTO drinksList VALUES(23,'','lime','juice',1,0);
INSERT INTO drinksList VALUES(24,'','lemon','juice',1,0);
INSERT INTO drinksList VALUES(25,'','grenadine','syrup',1,0);
INSERT INTO drinksList VALUES(26,'','spiced','rum',1,0);
INSERT INTO drinksList VALUES(27,'','dark','rum',1,0);
INSERT INTO drinksList VALUES(28,'','white','rum',1,0);
INSERT INTO drinksList VALUES(29,'','pineapple','fruit',0,1);
INSERT INTO drinksList VALUES(30,'','coconut','rum',1,0);
INSERT INTO drinksList VALUES(31,'','coconut','cream',0,0);
INSERT INTO drinksList VALUES(32,'','','sugar',1,1);
INSERT INTO drinksList VALUES(33,'','amaretto','liqueur',1,0);
INSERT INTO drinksList VALUES(34,'','vinnilla','vodka',0,0);
INSERT INTO drinksList VALUES(35,'','chocolate','liqueur',0,0);
INSERT INTO drinksList VALUES(36,'','scotch','whiskey',0,0);
INSERT INTO drinksList VALUES(37,'','rye','whiskey',0,0);
INSERT INTO drinksList VALUES(38,'jack daniel''s','honey','whiskey (burbon)',0,0);
INSERT INTO drinksList VALUES(39,'bailey''s','cream','liqueur',1,0);
INSERT INTO drinksList VALUES(40,'','','whiskey',1,0);
INSERT INTO drinksList VALUES(41,'','triple sec','liqueur',0,0);
INSERT INTO drinksList VALUES(42,'','coffee','liqueur',0,0);
INSERT INTO drinksList VALUES(43,'','curacao','liqueur',0,0);
INSERT INTO drinksList VALUES(44,'','prosecco','wine',0,0);
INSERT INTO drinksList VALUES(45,'','lemon','sorbet',0,0);
INSERT INTO drinksList VALUES(47,'','rosemary','herb',0,1);
INSERT INTO drinksList VALUES(50,'','vermoth','wine',0,0);
INSERT INTO drinksList VALUES(58,'','sweet','vermouth',0,0);
INSERT INTO drinksList VALUES(59,'','peychauds (licorice)','bitters',0,0);
INSERT INTO drinksList VALUES(60,'','campari','liqueur',0,0);
INSERT INTO drinksList VALUES(61,'','ginger','juice',0,0);
INSERT INTO drinksList VALUES(62,'','ginger','ale',0,0);
INSERT INTO drinksList VALUES(63,'','','soda',1,0);
INSERT INTO drinksList VALUES(64,'','grapefruit','juice',0,0);
INSERT INTO drinksList VALUES(65,'','benedictine','liqueur',0,0);
INSERT INTO drinksList VALUES(66,'','mint','leaves',0,1);
INSERT INTO drinksList VALUES(67,'','','bourbon',0,0);
INSERT INTO drinksList VALUES(68,'','old town','gin',0,0);
INSERT INTO drinksList VALUES(69,'','heavy','cream',0,1);
INSERT INTO drinksList VALUES(70,'','berries','fruit',0,0);
INSERT INTO drinksList VALUES(74,'','','salt',0,1);
INSERT INTO drinksList VALUES(75,'','','water',1,1);
INSERT INTO drinksList VALUES(76,'','black','pepper',0,1);
INSERT INTO drinksList VALUES(77,'','','honey',0,1);
INSERT INTO drinksList VALUES(78,'','coriander','herb',0,1);
INSERT INTO drinksList VALUES(79,'','apricot','brandy',0,0);
INSERT INTO drinksList VALUES(80,'','','champagne',0,0);
INSERT INTO drinksList VALUES(81,'','','brandy',0,0);
INSERT INTO drinksList VALUES(82,'','apple','brandy',0,0);
INSERT INTO drinksList VALUES(83,'','pisco','brandy',0,0);
INSERT INTO drinksList VALUES(84,'disorono','velvet','liqueur',0,0);
INSERT INTO drinksList VALUES(85,'','creme de cacao','liqueur',0,0);
INSERT INTO drinksList VALUES(86,'','espresso','coffee',0,1);
INSERT INTO drinksList VALUES(87,'','passoa','liqueur',0,0);
INSERT INTO drinksList VALUES(88,'','raspberry','fruit',0,0);
INSERT INTO drinksList VALUES(89,'','semi','milk',0,0);
INSERT INTO drinksList VALUES(90,'','','milk',0,1);
INSERT INTO drinksList VALUES(91,'','','ice',0,1);
INSERT INTO drinksList VALUES(92,'','white chocolate','liqueur',0,0);
INSERT INTO drinksList VALUES(93,'','','cointreau',0,0);
INSERT INTO drinksList VALUES(94,'','','cognac',0,0);
INSERT INTO drinksList VALUES(95,'','cherry','liqueur',0,0);
INSERT INTO drinksList VALUES(96,'','creme de cassis','liqueur',0,0);
INSERT INTO drinksList VALUES(97,'','almond','milk',0,0);
INSERT INTO drinksList VALUES(98,'','chambord','liqueur',0,0);
INSERT INTO drinksList VALUES(99,'','cucumber','veg',0,1);
INSERT INTO drinksList VALUES(100,'','rose','water',1,0);
INSERT INTO drinksList VALUES(101,'licor 43','vanilla','liqueur',0,0);
INSERT INTO drinksList VALUES(102,'','advocaat','liqueur',0,0);
INSERT INTO drinksList VALUES(103,'','basil','leaf',1,1);
INSERT INTO drinksList VALUES(104,'','orgeat (almond)','syrup',1,0);
INSERT INTO drinksList VALUES(105,'','respasado','tequila',1,0);
INSERT INTO drinksList VALUES(106,'mr black','coffee','liqueur',1,0);
INSERT INTO drinksList VALUES(107,'','creme de mure','liqueur',0,0);
INSERT INTO drinksList VALUES(108,'','lychee','juice',1,0);
COMMIT;