PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE recipeList (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL,method TEXT, rating REAL DEFAULT 0, notes TEXT);
INSERT INTO recipeList VALUES(4,'vodka cranberry','shake and serve. over ice if preferred',0.0,'');
INSERT INTO recipeList VALUES(5,'hole in one','float orange after mixing',0.0,'');
INSERT INTO recipeList VALUES(6,'burnso tropical','shake all together',0.0,'');
INSERT INTO recipeList VALUES(10,'dessert sunrise','half as needed',0.0,NULL);
INSERT INTO recipeList VALUES(11,'lemony snicket','shake all but grenadine. add splash and stir briefly',0.0,'quite fresh easy on the lemon. Made better by a dash or amoretto');
INSERT INTO recipeList VALUES(12,'loose caboose','shake 1-3. top with lemonade.',0.0,NULL);
INSERT INTO recipeList VALUES(13,'pine orgy','shake and serve',0.0,NULL);
INSERT INTO recipeList VALUES(20,'sex on the beach','shake',0.0,'');
INSERT INTO recipeList VALUES(21,'gin&sin','2 splashes of grenadine all shaken',0.0,NULL);
INSERT INTO recipeList VALUES(22,'ershammar dream','who knows just shake',0.0,NULL);
INSERT INTO recipeList VALUES(23,'georgia gin','probs shake',0.0,NULL);
INSERT INTO recipeList VALUES(24,'gin citric',replace('add grenadine last, or don''t i can''t tell you what to do\n\nshake or stir depending on qaulity of gin. top with extra orange depending on glass used','\n',char(10)),0.0,'');
INSERT INTO recipeList VALUES(25,'bailey''s madras','shake all bar cranberry. fill with cranberry',0.0,NULL);
INSERT INTO recipeList VALUES(26,'bahia breeze','build over ice garnish with lime',0.0,NULL);
INSERT INTO recipeList VALUES(27,'cabo','go light on lime. shake and strain',0.0,NULL);
INSERT INTO recipeList VALUES(28,'mexican punch','',0.0,NULL);
INSERT INTO recipeList VALUES(29,'loco lemonade','half recipe. build over ice. float lemon juice',0.0,NULL);
INSERT INTO recipeList VALUES(30,'mexicana',replace('small volume double cocktail \nshake all bar grenadine','\n',char(10)),0.0,'');
INSERT INTO recipeList VALUES(31,'shaker','it''s in the name',0.0,NULL);
INSERT INTO recipeList VALUES(32,'cinco de mayo','half this. 👀 shake with lots of ice',4.0,'');
INSERT INTO recipeList VALUES(33,'baby aspirine of humbolt','shake shake shake shake shake it',0.0,'');
INSERT INTO recipeList VALUES(34,'michael''s downfall','build or shake. 2 splashes grenadine, equal parts orange and cranberry to fill',0.0,'try kraken next time not rumbullion');
INSERT INTO recipeList VALUES(35,'bat bite','build over ice. full with cranberry',0.0,NULL);
INSERT INTO recipeList VALUES(36,'beaver shot','shake',0.0,'');
INSERT INTO recipeList VALUES(37,'bahama mama sunrise','',0.0,NULL);
INSERT INTO recipeList VALUES(38,'rum zombie','',1.5,'');
INSERT INTO recipeList VALUES(39,'pina colada','add all and blend',5.0,'');
INSERT INTO recipeList VALUES(40,'amaretto sour','heavy on lime if you like it sour. less if you like it sweet',5.0,NULL);
INSERT INTO recipeList VALUES(41,'rock bottom',replace('mix all except tequila, add slowly \n\ntry at your own peral','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(42,'bronze monkey','shake it',3.0,'');
INSERT INTO recipeList VALUES(43,'force 12','shake',0.0,NULL);
INSERT INTO recipeList VALUES(44,'orange flux','',0.0,NULL);
INSERT INTO recipeList VALUES(45,'plasse knock out','top with orange. shake',0.0,NULL);
INSERT INTO recipeList VALUES(46,'kingston','',2.0,'little bit heavier on lime');
INSERT INTO recipeList VALUES(47,'excuse me','top with lemonade after shake',0.0,'');
INSERT INTO recipeList VALUES(48,'nutty dream','',0.0,NULL);
INSERT INTO recipeList VALUES(49,'sax with t','top with equal pinapple and orange. 1-2 parts amaretto',5.0,'');
INSERT INTO recipeList VALUES(50,'scottalian','shake all  add grenadine last ( can half)',3.0,'');
INSERT INTO recipeList VALUES(51,'snikertini','sub choc liqueur with second part bailey s',5.0,'better with choc Bailey''s');
INSERT INTO recipeList VALUES(52,'whiskey sour','shake hard and fast 20s strain',4.0,NULL);
INSERT INTO recipeList VALUES(53,'screaming o','dry shake first top with whipped cream creme de cacao and hazelnut syrup',3.5,'');
INSERT INTO recipeList VALUES(54,'irish american','coconut rum optional',5.0,NULL);
INSERT INTO recipeList VALUES(55,'jamaican sunrise','float cranberry',0.0,'');
INSERT INTO recipeList VALUES(56,'blue hawaiian','add all and shake for radio active green',3.0,'');
INSERT INTO recipeList VALUES(57,'sgroppino','scoop of lemon sorbet mix by hand to avoid over melting',0.0,'');
INSERT INTO recipeList VALUES(59,'dirty dianne','',2.5,NULL);
INSERT INTO recipeList VALUES(60,'old fashioned',replace('large ice and stir\n\ncan sub rye for bourbon \n\ntypically use sugar cube instead of syrup','\n',char(10)),4.0,'');
INSERT INTO recipeList VALUES(61,'manhattan',replace('stirred not shaken 30s \n\nadd luxardo cherry if possible','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(62,'sazerac','stirred',0.0,NULL);
INSERT INTO recipeList VALUES(63,'whisky fix',replace('can sub bourbon for rye\n\nwhip (single ice dissolved)\n\ncrushed ice if possible','\n',char(10)),3.5,NULL);
INSERT INTO recipeList VALUES(64,'boulevardier',replace('briefly stir\n\ngarnish with orange twist','\n',char(10)),3.5,replace('some recipes call for equal parts \n\nbetter as small volume. 3 is a lot','\n',char(10)));
INSERT INTO recipeList VALUES(65,'presbyterian',replace('soda to ale ratio to desired taste\n\ncan sub ale for fresh ginger juice\n\nwhip lime and rye and build over ice','\n',char(10)),0.0,'');
INSERT INTO recipeList VALUES(66,'blinker','shake',4.0,'remember to shake grapefruit juice / add some passoa');
INSERT INTO recipeList VALUES(67,'monte carlo',replace('2- 3 parts rye\n\ngood stir\n\ngarnish with lemon twist','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(68,'mint julep',replace('2+ of bourbon\nmuddle in glass \n\noptional garnish with rum','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(69,'martini',replace('stir with ice \n\ngarnish with olive or lemon twist','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(70,'martínez','garnish with lemon twist',0.0,NULL);
INSERT INTO recipeList VALUES(71,'gimlet','shake',4.0,NULL);
INSERT INTO recipeList VALUES(72,'negroni',replace('orange twist garnish\n\nbuild over ice','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(73,'tom collins',replace('whip \n\ntop with soda','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(75,'bramble',replace('dry shake without gin\n\nadd to crushed ice and stir','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(76,'spiked','blend with cup of ice',0.0,'');
INSERT INTO recipeList VALUES(77,'senku','can use soda or lemonade. adjust honey and lemon if using lemonade.',0.0,NULL);
INSERT INTO recipeList VALUES(78,'daiquiri','go light on lime or heavy on sugar to taste',0.0,NULL);
INSERT INTO recipeList VALUES(79,'americano',replace('build in glass \n\ngarnish with orange \n\nlemonade or soda depending on preference','\n',char(10)),4.0,'');
INSERT INTO recipeList VALUES(80,'margaritas',replace('up lime / optional sugar syrup\n\nshake and rim glass with lime+flakey salt','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(81,'mexican firing squad','shake  can top with soda  and orange twist',3.5,replace('solid tequila cocktail similar to margarita\n\ncould be sweater?','\n',char(10)));
INSERT INTO recipeList VALUES(82,'mai tai',replace('whip serve on crushed ice with mint\n\noptional lime juice','\n',char(10)),4.0,replace('only got such a high rating with coconut rum\n\ncomes out a beautiful emerald with rumbullion\ncould use a touch of sweetness','\n',char(10)));
INSERT INTO recipeList VALUES(83,'mojito','dry shake and  over  crushed ice',0.0,NULL);
INSERT INTO recipeList VALUES(84,'hotel national special','top with bitters',0.0,NULL);
INSERT INTO recipeList VALUES(85,'french 75','shake all but champagne use to top',3.5,NULL);
INSERT INTO recipeList VALUES(86,'pink lady','whip into coup bitters to top',5.0,replace('whip gently\n\nif doubling 1 med-large egg is enough','\n',char(10)));
INSERT INTO recipeList VALUES(87,'jack rose','',0.0,NULL);
INSERT INTO recipeList VALUES(88,'champagne cocktail',replace('drop sugar cube to bottom of glass\ngenerously coat in bitters\nchampagne to fill','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(89,'pisco sour',replace('shake well strain into coup\ntop with orange bitters or cinnamon','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(90,'long island iced tea',replace('mix everything but cola in shaker use coke to top\n\ncan go heavier on lime','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(91,'amf',replace('shake all bar lemonade use to fill  \n\ncan go heavier on lime','\n',char(10)),3.0,'try with better lemonade');
INSERT INTO recipeList VALUES(92,'cosmopolitan','shake all',2.0,'very strong vodka tasting cocktail. try upping  lemon a tad or adding 0.5 of sugar');
INSERT INTO recipeList VALUES(93,'tropical pink  missy','whip',4.0,NULL);
INSERT INTO recipeList VALUES(94,'mexican  sunset','',3.0,'little bit too pinapple, still nice maybe add some lime?');
INSERT INTO recipeList VALUES(95,'nutty mudslide','dry shake then wet then strain over ice',3.5,NULL);
INSERT INTO recipeList VALUES(96,'nutty mudslide #2','dry then wet then strain',0.0,NULL);
INSERT INTO recipeList VALUES(97,'mudslide','',0.0,NULL);
INSERT INTO recipeList VALUES(98,'sweet mudslide','can up vanilla vodka (1.5) if low alcohol',4.5,'');
INSERT INTO recipeList VALUES(99,'sex with the captain','build over ice use equal cranberry and orange to fill',3.5,NULL);
INSERT INTO recipeList VALUES(100,'espresso martini',replace('optional 5ml sugar syrup. \ncan play with ratios all in cup and shake','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(101,'espresso martini #2',replace('shake and double strain.\n\ntry with vanilla vodka !','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(102,'ghost goblet',replace('cointreau and white cranberry recommend \n\nshake and strain into martini glass','\n',char(10)),4.0,'essentially a vodka cranberry with an orange twist. quite strong');
INSERT INTO recipeList VALUES(103,'punch in the head',replace('shake into large tiki glass\n\noptional: garnish orange/cherry','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(104,'baby vox','stirred not shaken 👀',4.0,'grenadine and or amaretto');
INSERT INTO recipeList VALUES(105,'big red hoot','build over colin''s glass fill with pineapple',3.0,NULL);
INSERT INTO recipeList VALUES(106,'cowgirl quencher','build over crushed ice add grenadine at the end',4.5,'not very fancy but nice change in flavour as you drink');
INSERT INTO recipeList VALUES(107,'mexican prison cocktail','',0.0,NULL);
INSERT INTO recipeList VALUES(108,'fubar kool-aid','',4.0,'try with dark rum or remove');
INSERT INTO recipeList VALUES(109,'red headed woodpecker','shake into collins cranberry to fill and turn drink red',5.0,'splash of grenadine nice add. not very alcoholic but very nice');
INSERT INTO recipeList VALUES(110,'passoa bramble','shake all but grenadine',3.0,'light citrus refreshing. go light on lemon/heavy on sugar');
INSERT INTO recipeList VALUES(111,'pink hawaiian passion','shake for nice pinapple head',4.0,NULL);
INSERT INTO recipeList VALUES(112,'raspberry mandarin',replace('blend rasberries grenadine and sugar syrup pinch salt and a dash of lime \n\noptional passoa doesn''t add much\n\nshake with rest and double strain','\n',char(10)),5.0,NULL);
INSERT INTO recipeList VALUES(113,'almond joy','',0.0,NULL);
INSERT INTO recipeList VALUES(114,'almond joy #2','',5.0,NULL);
INSERT INTO recipeList VALUES(115,'terry''s martini','',0.0,NULL);
INSERT INTO recipeList VALUES(116,'tiramisú','shake and strain into coup or other small volume',4.0,NULL);
INSERT INTO recipeList VALUES(117,'chocolate lady','whip ? small volume',2.5,'sweet and sour, like lemon sour');
INSERT INTO recipeList VALUES(118,'crooked sisters','shake into small volume',3.5,'very similar to Terry''s');
INSERT INTO recipeList VALUES(119,'ramos gin fizz','dry shake then whip with descent ice top with soda',3.5,'');
INSERT INTO recipeList VALUES(120,'french 75 #2','fill about half with champagne or other sparkling wine . shake the rest and pour over champagne',0.0,NULL);
INSERT INTO recipeList VALUES(121,'raspberry sniket','add half of grenadine to shake and half after',5.0,NULL);
INSERT INTO recipeList VALUES(122,'florida rain','shake and strain  into collins or half and into coup',4.0,NULL);
INSERT INTO recipeList VALUES(123,'high risk society','shake throughly cold and double strain into coup',4.5,replace('sweet and sour with a nice hit of cherry\n\ncareful not to over dilute','\n',char(10)));
INSERT INTO recipeList VALUES(124,'naked pink (a barbie)','add all and shake with large ice vigorously  double strain',4.5,'comes out pale frothy pink. does 2 coupes');
INSERT INTO recipeList VALUES(125,'cherry cobbler','shake and strain',3.0,NULL);
INSERT INTO recipeList VALUES(126,'captain''s french kiss','shake all but champagne. use to fill wine glass',3.5,NULL);
INSERT INTO recipeList VALUES(127,'captain''s colada','',5.0,NULL);
INSERT INTO recipeList VALUES(128,'oreo martini','shake and double strain into coup',5.0,NULL);
INSERT INTO recipeList VALUES(129,'strawberry shortcake','well mix, shake and double strain',3.0,NULL);
INSERT INTO recipeList VALUES(130,'french martini','shake all and garnished with pineapple',0.0,NULL);
INSERT INTO recipeList VALUES(131,'romeo and juliet',replace('muddle cucumber and salt \nshake everything \ndouble strain\n\ngarnish with mint rose water and angustura bitters \n\n3drops rose water','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(132,'cream egg','',0.0,NULL);
INSERT INTO recipeList VALUES(133,'basil orgeat lemon',replace('quick shake\ninto crushed ice with basil\ntop with soda','\n',char(10)),0.0,NULL);
INSERT INTO recipeList VALUES(134,'lemon delight','',4.0,NULL);
INSERT INTO recipeList VALUES(135,'mexican mia tai','shake all into tikki or coup',3.5,'bit sweet could try with Curacao instead');
INSERT INTO recipeList VALUES(136,'white lady','whip',0.0,'');
INSERT INTO recipeList VALUES(137,'twilight in queens','',0.0,NULL);
INSERT INTO recipeList VALUES(138,'raspberry blossom',replace('shake, possibly whip\ngrenadine in at end','\n',char(10)),0.0,'previously made with specific rasberry vinilla margarine gin. so sweet sour alcohol balance might be off');
INSERT INTO recipeList VALUES(139,'mr blacks martini','',4.0,NULL);
INSERT INTO recipeList VALUES(140,'rasberry rose',replace('blend all but lemonade \n\nup lemon juice/sugar depending on taste','\n',char(10)),5.0,NULL);
INSERT INTO recipeList VALUES(141,'tequila and mint','tbd',0.0,NULL);
INSERT INTO recipeList VALUES(142,'green demon','',0.0,NULL);
INSERT INTO recipeList VALUES(143,'purple rain','blue curacao for namesake',0.0,NULL);
COMMIT;