INSERT INTO recipeList VALUES
(4,'vodka cranberry','shake and serve. over ice if preferred',0.0,''),
(5,'hole in one','float orange after mixing',0.0,''),
(6,'burnso tropical','shake all together',0.0,''),
(10,'dessert sunrise','half as needed',0.0,NULL),
(11,'lemony snicket','shake all but grenadine. add splash and stir briefly',0.0,'quite fresh easy on the lemon. Made better by a dash or amoretto'),
(12,'loose caboose','shake 1-3. top with lemonade.',0.0,NULL),
(13,'pine orgy','shake and serve',0.0,NULL),
(20,'sex on the beach','shake',0.0,''),
(21,'gin&sin','2 splashes of grenadine all shaken',0.0,NULL),
(22,'ershammar dream','who knows just shake',0.0,NULL),
(23,'georgia gin','probs shake',0.0,NULL),
(24,'gin citric','add grenadine last, or don''t i can''t tell you what to do' || '\n' || '\n' || 'shake or stir depending on qaulity of gin. top with extra orange depending on glass used',0.0,''),
(25,'bailey''s madras','shake all bar cranberry. fill with cranberry',0.0,NULL),
(26,'bahia breeze','build over ice garnish with lime',0.0,NULL),
(27,'cabo','go light on lime. shake and strain',0.0,NULL),
(28,'mexican punch','',0.0,NULL),
(29,'loco lemonade','half recipe. build over ice. float lemon juice',0.0,NULL),
(30,'mexicana','small volume double cocktail ' || '\n' || 'hake all bar grenadine',0.0,''),
(31,'shaker','it''s in the name',0.0,NULL),
(32,'cinco de mayo','half this. 👀 shake with lots of ice',4.0,''),
(33,'baby aspirine of humbolt','shake shake shake shake shake it',0.0,''),
(34,'michael''s downfall','build or shake. 2 splashes grenadine, equal parts orange and cranberry to fill',0.0,'try kraken next time not rumbullion'),
(35,'bat bite','build over ice. full with cranberry',0.0,NULL),
(36,'beaver shot','shake',0.0,''),
(37,'bahama mama sunrise','',0.0,NULL),
(38,'rum zombie','',1.5,''),
(39,'pina colada','add all and blend',5.0,''),
(40,'amaretto sour','heavy on lime if you like it sour. less if you like it sweet',5.0,NULL),
(41,'rock bottom','mix all except tequila, add slowly ' || '\n' || '\n' || 'try at your own peral',0.0,NULL),
(42,'bronze monkey','shake it',3.0,''),
(43,'force 12','shake',0.0,NULL),
(44,'orange flux','',0.0,NULL),
(45,'plasse knock out','top with orange. shake',0.0,NULL),
(46,'kingston','',2.0,'little bit heavier on lime'),
(47,'excuse me','top with lemonade after shake',0.0,''),
(48,'nutty dream','',0.0,NULL),
(49,'sax with t','top with equal pinapple and orange. 1-2 parts amaretto',5.0,''),
(50,'scottalian','shake all  add grenadine last ( can half)',3.0,''),
(51,'snikertini','sub choc liqueur with second part bailey s',5.0,'better with choc Bailey''s'),
(52,'whiskey sour','shake hard and fast 20s strain',4.0,NULL),
(53,'screaming o','dry shake first top with whipped cream creme de cacao and hazelnut syrup',3.5,''),
(54,'irish american','coconut rum optional',5.0,NULL),
(55,'jamaican sunrise','float cranberry',0.0,''),
(56,'blue hawaiian','add all and shake for radio active green',3.0,''),
(57,'sgroppino','scoop of lemon sorbet mix by hand to avoid over melting',0.0,''),
(59,'dirty dianne','',2.5,NULL),
(60,'old fashioned','large ice and stir' || '\n' || '\n' || 'can sub rye for bourbon ' || '\n' || '\n' || 'typically use sugar cube instead of syrup',4.0,''),
(61,'manhattan','stirred not shaken 30s ' || '\n' || '\n' || 'add luxardo cherry if possible',0.0,NULL),
(62,'sazerac','stirred',0.0,NULL),
(63,'whisky fix','can sub bourbon for rye' || '\n' || '\n' || 'whip (single ice dissolved)' || '\n' || '\n' || 'crushed ice if possible',3.5,NULL),
(64,'boulevardier','briefly stir' || '\n' || '\n' || 'garnish with orange twist',3.5,'some recipes call for equal parts ' || '\n' || '\n' || 'better as small volume. 3 is a lot'),
(65,'presbyterian','soda to ale ratio to desired taste' || '\n' || '\n' || 'can sub ale for fresh ginger juice' || '\n' || '\n' || 'whip lime and rye and build over ice',0.0,''),
(66,'blinker','shake',4.0,'remember to shake grapefruit juice / add some passoa'),
(67,'monte carlo','2- 3 parts rye' || '\n' || '\n' || 'good stir' || '\n' || '\n' || 'garnish with lemon twist',0.0,NULL),
(68,'mint julep','2+ of bourbon' || '\n' || 'uddle in glass ' || '\n' || '\n' || 'optional garnish with rum',0.0,NULL),
(69,'martini','stir with ice ' || '\n' || '\n' || 'garnish with olive or lemon twist',0.0,NULL),
(70,'martínez','garnish with lemon twist',0.0,NULL),
(71,'gimlet','shake',4.0,NULL),
(72,'negroni','orange twist garnish' || '\n' || '\n' || 'build over ice',0.0,NULL),
(73,'tom collins','whip ' || '\n' || '\n' || 'top with soda',0.0,NULL),
(75,'bramble','dry shake without gin' || '\n' || '\n' || 'add to crushed ice and stir',0.0,NULL),
(76,'spiked','blend with cup of ice',0.0,''),
(77,'senku','can use soda or lemonade. adjust honey and lemon if using lemonade.',0.0,NULL),
(78,'daiquiri','go light on lime or heavy on sugar to taste',0.0,NULL),
(79,'americano','build in glass ' || '\n' || '\n' || 'garnish with orange ' || '\n' || '\n' || 'lemonade or soda depending on preference',4.0,''),
(80,'margaritas','up lime / optional sugar syrup' || '\n' || '\n' || 'shake and rim glass with lime+flakey salt',0.0,NULL),
(81,'mexican firing squad','shake  can top with soda  and orange twist',3.5,'solid tequila cocktail similar to margarita' || '\n' || '\n' || 'could be sweater?'),
(82,'mai tai','whip serve on crushed ice with mint' || '\n' || '\n' || 'optional lime juice',4.0,'only got such a high rating with coconut rum' || '\n' || '\n' || 'comes out a beautiful emerald with rumbullion' || '\n' || 'ould use a touch of sweetness'),
(83,'mojito','dry shake and  over  crushed ice',0.0,NULL),
(84,'hotel national special','top with bitters',0.0,NULL),
(85,'french 75','shake all but champagne use to top',3.5,NULL),
(86,'pink lady','whip into coup bitters to top',5.0,'whip gently' || '\n' || '\n' || 'if doubling 1 med-large egg is enough'),
(87,'jack rose','',0.0,NULL),
(88,'champagne cocktail','drop sugar cube to bottom of glass' || '\n' || 'enerously coat in bitters' || '\n' || 'hampagne to fill',0.0,NULL),
(89,'pisco sour','shake well strain into coup' || '\n' || 'op with orange bitters or cinnamon',0.0,NULL),
(90,'long island iced tea','mix everything but cola in shaker use coke to top' || '\n' || '\n' || 'can go heavier on lime',0.0,NULL),
(91,'amf','shake all bar lemonade use to fill  ' || '\n' || '\n' || 'can go heavier on lime',3.0,'try with better lemonade'),
(92,'cosmopolitan','shake all',2.0,'very strong vodka tasting cocktail. try upping  lemon a tad or adding 0.5 of sugar'),
(93,'tropical pink  missy','whip',4.0,NULL),
(94,'mexican  sunset','',3.0,'little bit too pinapple, still nice maybe add some lime?'),
(95,'nutty mudslide','dry shake then wet then strain over ice',3.5,NULL),
(96,'nutty mudslide #2','dry then wet then strain',0.0,NULL),
(97,'mudslide','',0.0,NULL),
(98,'sweet mudslide','can up vanilla vodka (1.5) if low alcohol',4.5,''),
(99,'sex with the captain','build over ice use equal cranberry and orange to fill',3.5,NULL),
(100,'espresso martini','optional 5ml sugar syrup. ' || '\n' || 'an play with ratios all in cup and shake',0.0,NULL),
(101,'espresso martini #2','shake and double strain.' || '\n' || '\n' || 'try with vanilla vodka !',0.0,NULL),
(102,'ghost goblet','cointreau and white cranberry recommend ' || '\n' || '\n' || 'shake and strain into martini glass',4.0,'essentially a vodka cranberry with an orange twist. quite strong'),
(103,'punch in the head','shake into large tiki glass' || '\n' || '\n' || 'optional: garnish orange/cherry',0.0,NULL),
(104,'baby vox','stirred not shaken 👀',4.0,'grenadine and or amaretto'),
(105,'big red hoot','build over colin''s glass fill with pineapple',3.0,NULL),
(106,'cowgirl quencher','build over crushed ice add grenadine at the end',4.5,'not very fancy but nice change in flavour as you drink'),
(107,'mexican prison cocktail','',0.0,NULL),
(108,'fubar kool-aid','',4.0,'try with dark rum or remove'),
(109,'red headed woodpecker','shake into collins cranberry to fill and turn drink red',5.0,'splash of grenadine nice add. not very alcoholic but very nice'),
(110,'passoa bramble','shake all but grenadine',3.0,'light citrus refreshing. go light on lemon/heavy on sugar'),
(111,'pink hawaiian passion','shake for nice pinapple head',4.0,NULL),
(112,'raspberry mandarin','blend rasberries grenadine and sugar syrup pinch salt and a dash of lime ' || '\n' || '\n' || 'optional passoa doesn''t add much' || '\n' || '\n' || 'shake with rest and double strain',5.0,NULL),
(113,'almond joy','',0.0,NULL),
(114,'almond joy #2','',5.0,NULL),
(115,'terry''s martini','',0.0,NULL),
(116,'tiramisú','shake and strain into coup or other small volume',4.0,NULL),
(117,'chocolate lady','whip ? small volume',2.5,'sweet and sour, like lemon sour'),
(118,'crooked sisters','shake into small volume',3.5,'very similar to Terry''s'),
(119,'ramos gin fizz','dry shake then whip with descent ice top with soda',3.5,''),
(120,'french 75 #2','fill about half with champagne or other sparkling wine . shake the rest and pour over champagne',0.0,NULL),
(121,'raspberry sniket','add half of grenadine to shake and half after',5.0,NULL),
(122,'florida rain','shake and strain  into collins or half and into coup',4.0,NULL),
(123,'high risk society','shake throughly cold and double strain into coup',4.5,'sweet and sour with a nice hit of cherry' || '\n' || '\n' || 'careful not to over dilute'),
(124,'naked pink (a barbie)','add all and shake with large ice vigorously  double strain',4.5,'comes out pale frothy pink. does 2 coupes'),
(125,'cherry cobbler','shake and strain',3.0,NULL),
(126,'captain''s french kiss','shake all but champagne. use to fill wine glass',3.5,NULL),
(127,'captain''s colada','',5.0,NULL),
(128,'oreo martini','shake and double strain into coup',5.0,NULL),
(129,'strawberry shortcake','well mix, shake and double strain',3.0,NULL),
(130,'french martini','shake all and garnished with pineapple',0.0,NULL),
(131,'romeo and juliet','muddle cucumber and salt ' || '\n' || 'hake everything ' || '\n' || 'ouble strain' || '\n' || '\n' || 'garnish with mint rose water and angustura bitters ' || '\n' || '\n' || '3drops rose water',0.0,NULL),
(132,'cream egg','',0.0,NULL),
(133,'basil orgeat lemon','quick shake' || '\n' || 'nto crushed ice with basil' || '\n' || 'op with soda',0.0,NULL),
(134,'lemon delight','',4.0,NULL),
(135,'mexican mia tai','shake all into tikki or coup',3.5,'bit sweet could try with Curacao instead'),
(136,'white lady','whip',0.0,''),
(137,'twilight in queens','',0.0,NULL),
(138,'raspberry blossom','shake, possibly whip' || '\n' || 'renadine in at end',0.0,'previously made with specific rasberry vinilla margarine gin. so sweet sour alcohol balance might be off'),
(139,'mr blacks martini','',4.0,NULL),
(140,'rasberry rose','blend all but lemonade ' || '\n' || '\n' || 'up lemon juice/sugar depending on taste',5.0,NULL),
(141,'tequila and mint','tbd',0.0,NULL),
(142,'green demon','',0.0,NULL),
(143,'purple rain','blue curacao for namesake',0.0,NULL);